---
version: '3'
services:

  # App BookStack
  bookstack:
    image: solidnerd/bookstack:22.04
    container_name: bookstack
    restart: unless-stopped
    environment:
      - DB_HOST=bookstack_db:3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=bookstack
      - DB_PASSWORD=secret
      - APP_URL=http://bookstack:8080
    #ports:
    #  - 8080:8080
    depends_on:
      - bookstack_db
    networks:
      - bookstack-network

  # DB BookStack
  bookstack_db:
    image: mysql:5.7.21
    container_name: bookstack_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=secret
    networks:
      - bookstack-network

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    #tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /bookstack/nginx/conf.d/:/etc/nginx/conf.d/
      - /bookstack/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - bookstack-network

#Docker Networks
networks:
  bookstack-network:
    driver: bridge
