version: '2'
services:

  db:
    environment:
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mattermost
    image: postgres:11.12

  mattermost:
    image: mattermost/mattermost-team-edition
    links:
    - db:db
    environment:
    - MM_USERNAME=mmuser
    - MM_PASSWORD=mmuser_password
    - MM_DBNAME=mattermost
    - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:password@db:5432/mattermost?sslmode=disable&connect_timeout=10
    ports:
    - 4000:8065